import assert from "node:assert/strict";
import { chmod, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { platformTargetTriple, stageAgentWorker } from "./stageWorker.mjs";

test("platformTargetTriple maps supported release targets", () => {
  assert.equal(platformTargetTriple("darwin", "arm64"), "aarch64-apple-darwin");
  assert.equal(platformTargetTriple("darwin", "x64"), "x86_64-apple-darwin");
  assert.equal(platformTargetTriple("linux", "arm64"), "aarch64-unknown-linux-gnu");
  assert.equal(platformTargetTriple("linux", "x64"), "x86_64-unknown-linux-gnu");
  assert.equal(platformTargetTriple("win32", "x64"), "x86_64-pc-windows-msvc");
});

test("stageAgentWorker copies worker project and node runtime", async (t) => {
  const root = await mkdtemp(join(tmpdir(), "openkoto-stage-worker-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const desktopDir = join(root, "textlingo-desktop");
  const workerDir = join(root, "agent-worker");
  const nodeExecutable = join(root, "node");
  await mkdir(join(workerDir, "dist"), { recursive: true });
  await mkdir(join(workerDir, "node_modules", "@opencode-ai", "sdk"), { recursive: true });
  await mkdir(join(workerDir, "node_modules", "zod"), { recursive: true });
  await mkdir(
    join(workerDir, "node_modules", "opencode-darwin-arm64", "bin"),
    { recursive: true },
  );
  await mkdir(
    join(desktopDir, "src-tauri", "resources", "agent-worker", "bin"),
    { recursive: true },
  );
  await writeFile(join(workerDir, "dist", "index.js"), "console.log('worker');\n");
  await writeFile(join(workerDir, "package.json"), '{"type":"module"}\n');
  await writeFile(
    join(workerDir, "node_modules", "@opencode-ai", "sdk", "package.json"),
    '{"name":"@opencode-ai/sdk"}\n',
  );
  await writeFile(
    join(workerDir, "node_modules", "zod", "package.json"),
    '{"name":"zod"}\n',
  );
  await writeFile(
    join(workerDir, "node_modules", "opencode-darwin-arm64", "bin", "opencode"),
    "opencode-runtime",
  );
  await writeFile(
    join(desktopDir, "src-tauri", "resources", "agent-worker", "bin", "stale-runtime"),
    "stale",
  );
  const staleNodeDestination = join(
    desktopDir,
    "src-tauri",
    "binaries",
    "openkoto-agent-node-aarch64-apple-darwin",
  );
  await mkdir(join(desktopDir, "src-tauri", "binaries"), { recursive: true });
  await writeFile(staleNodeDestination, "stale-node");
  await chmod(staleNodeDestination, 0o555);
  await writeFile(nodeExecutable, "node-runtime");
  let verifiedNodeRuntime = null;

  const result = await stageAgentWorker({
    desktopDir,
    workerDir,
    nodeExecutable,
    platform: "darwin",
    arch: "arm64",
    async verifyNodeRuntime(stagedNodeRuntime) {
      verifiedNodeRuntime = stagedNodeRuntime;
      assert.equal(await readFile(stagedNodeRuntime, "utf8"), "node-runtime");
    },
  });

  assert.equal(
    await readFile(join(result.workerDestination, "dist", "index.js"), "utf8"),
    "console.log('worker');\n",
  );
  assert.equal(
    await readFile(join(result.workerDestination, ".gitkeep"), "utf8"),
    "# Generated by npm run stage during builds.\n",
  );
  assert.equal(
    await readFile(
      join(
        result.workerDestination,
        "node_modules",
        "@opencode-ai",
        "sdk",
        "package.json",
      ),
      "utf8",
    ),
    '{"name":"@opencode-ai/sdk"}\n',
  );
  assert.equal(await readFile(result.opencodeDestination, "utf8"), "opencode-runtime");
  assert.equal(await readFile(result.nodeDestination, "utf8"), "node-runtime");
  assert.equal(verifiedNodeRuntime, result.nodeDestination);
  await assert.rejects(
    readFile(join(result.workerDestination, "bin", "stale-runtime"), "utf8"),
    { code: "ENOENT" },
  );
  assert.match(result.opencodeDestination, /opencode-aarch64-apple-darwin$/);
  assert.match(result.nodeDestination, /openkoto-agent-node-aarch64-apple-darwin$/);
});
