import { execFile } from "node:child_process";
import { chmod, copyFile, cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);

const TARGETS = new Map([
  ["darwin:arm64", "aarch64-apple-darwin"],
  ["darwin:x64", "x86_64-apple-darwin"],
  ["linux:arm64", "aarch64-unknown-linux-gnu"],
  ["linux:x64", "x86_64-unknown-linux-gnu"],
  ["win32:x64", "x86_64-pc-windows-msvc"],
]);

export function platformTargetTriple(platform, arch) {
  const target = TARGETS.get(`${platform}:${arch}`);
  if (!target) {
    throw new Error(`Unsupported agent worker target: ${platform}/${arch}`);
  }
  return target;
}

function opencodeRuntimePackage(platform, arch) {
  const platformName = platform === "win32" ? "windows" : platform;
  const baseline = arch === "x64" ? "-baseline" : "";
  return `opencode-${platformName}-${arch}${baseline}`;
}

function buildStagePaths(options) {
  const workerDestination = join(
    options.desktopDir,
    "src-tauri",
    "resources",
    "agent-worker",
  );
  const executableSuffix = options.platform === "win32" ? ".exe" : "";
  const opencodeName = options.platform === "win32" ? "opencode.exe" : "opencode";
  const target = platformTargetTriple(options.platform, options.arch);
  const binariesDir = join(options.desktopDir, "src-tauri", "binaries");
  return {
    workerDestination,
    nodeDestination: join(
      binariesDir,
      `openkoto-agent-node-${target}${executableSuffix}`,
    ),
    opencodeDestination: join(binariesDir, `opencode-${target}${executableSuffix}`),
    opencodeSource: join(
      options.workerDir,
      "node_modules",
      opencodeRuntimePackage(options.platform, options.arch),
      "bin",
      opencodeName,
    ),
  };
}

async function copyWorkerRuntime(options, paths) {
  await Promise.all([
    cp(join(options.workerDir, "dist"), join(paths.workerDestination, "dist"), {
      recursive: true,
    }),
    cp(
      join(options.workerDir, "node_modules", "@opencode-ai", "sdk"),
      join(paths.workerDestination, "node_modules", "@opencode-ai", "sdk"),
      { recursive: true },
    ),
    cp(
      join(options.workerDir, "node_modules", "zod"),
      join(paths.workerDestination, "node_modules", "zod"),
      { recursive: true },
    ),
    copyFile(paths.opencodeSource, paths.opencodeDestination),
    copyFile(
      join(options.workerDir, "package.json"),
      join(paths.workerDestination, "package.json"),
    ),
    copyFile(options.nodeExecutable, paths.nodeDestination),
  ]);
}

async function verifyStagedNodeRuntime(nodeExecutable) {
  try {
    const { stdout } = await execFileAsync(nodeExecutable, ["--version"]);
    if (!/^v\d+\./.test(stdout.trim())) {
      throw new Error(`unexpected version output: ${stdout.trim()}`);
    }
  } catch (error) {
    throw new Error(
      `Staged Node runtime is not self-contained: ${nodeExecutable} failed to start after copying. ` +
        `Use a portable Node distribution (for example actions/setup-node or nvm). ` +
        `${error instanceof Error ? error.message : String(error)}`,
    );
  }
}

export async function stageAgentWorker(options) {
  const paths = buildStagePaths(options);
  await Promise.all([
    rm(paths.workerDestination, { recursive: true, force: true }),
    rm(paths.nodeDestination, { force: true }),
    rm(paths.opencodeDestination, { force: true }),
  ]);
  await Promise.all([
    mkdir(join(paths.workerDestination, "node_modules", "@opencode-ai"), {
      recursive: true,
    }),
    mkdir(dirname(paths.nodeDestination), { recursive: true }),
  ]);
  await writeFile(
    join(paths.workerDestination, ".gitkeep"),
    "# Generated by npm run stage during builds.\n",
  );
  await copyWorkerRuntime(options, paths);
  if (options.platform !== "win32") {
    await Promise.all([
      chmod(paths.nodeDestination, 0o755),
      chmod(paths.opencodeDestination, 0o755),
    ]);
  }
  await (options.verifyNodeRuntime ?? verifyStagedNodeRuntime)(
    paths.nodeDestination,
  );
  return {
    workerDestination: paths.workerDestination,
    nodeDestination: paths.nodeDestination,
    opencodeDestination: paths.opencodeDestination,
  };
}

async function main() {
  const workerDir = dirname(fileURLToPath(import.meta.url));
  const result = await stageAgentWorker({
    desktopDir: dirname(workerDir),
    workerDir,
    nodeExecutable:
      process.env.OPENKOTO_AGENT_NODE_EXECUTABLE || process.execPath,
    platform: process.platform,
    arch: process.arch,
  });
  process.stdout.write(
    `Staged agent worker: ${result.workerDestination}\nStaged Node runtime: ${result.nodeDestination}\nStaged OpenCode runtime: ${result.opencodeDestination}\n`,
  );
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
